'use strict';
// Builds artifact/dist/coach-desk.html: the whole app (routes, views, SQL) running in the browser.
// Usage: node artifact/build.js
const fs = require('fs');
const path = require('path');
const ejs = require('ejs');
const esbuild = require('esbuild');

const root = path.join(__dirname, '..');
const out = path.join(__dirname, '.build');
fs.mkdirSync(out, { recursive: true });
fs.mkdirSync(path.join(__dirname, 'dist'), { recursive: true });

// 1. Pre-compile every EJS view into a client function (no eval at runtime).
function viewFiles(dir, prefix = '') {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((d) =>
    d.isDirectory() ? viewFiles(path.join(dir, d.name), `${prefix}${d.name}/`) : d.name.endsWith('.ejs') ? [`${prefix}${d.name.slice(0, -4)}`] : []);
}
function adapt(name, src) {
  // confirm() is blocked in artifacts: turn it into a two-tap confirm handled by main.js
  src = src.replace(/on(?:submit|click)="return confirm\('([^']*)'\)"/g, 'data-confirm="$1"');
  if (name === 'partials/head') {
    src = src.replace(/<!doctype html>|<\/?html[^>]*>|<\/?head>|<meta[^>]*>|<title>.*<\/title>|<link rel="stylesheet"[^>]*>|<body>/gi, '');
  }
  if (name === 'partials/foot') src = src.replace(/<\/body>|<\/html>/g, '');
  if (name === 'session-print') {
    src = src
      .replace(/<!doctype html>|<\/?html[^>]*>|<\/?head>|<meta[^>]*>|<title>.*<\/title>|<\/?body>/gi, '')
      .replace(/@page[^}]*}/, '')
      .replace(/\bbody \{/g, '.sp {')
      .replace(/<button onclick="window.print\(\)">Print<\/button>\s*/, '');
    src = `<main><div class="sp">${src}</div></main>`;
  }
  return src;
}
const names = viewFiles(path.join(root, 'views'));
// Emitted as its own classic (non-strict) script: compiled EJS uses `with`, which strict-mode bundles forbid.
let tpl = '// generated by artifact/build.js\nwindow.__CD_TEMPLATES = {\n';
for (const n of names) {
  const src = adapt(n, fs.readFileSync(path.join(root, 'views', `${n}.ejs`), 'utf8'));
  // EJS 6 wraps compiled functions in a server-side closure, so take the generated body instead.
  const t = new ejs.Template(src, { compileDebug: false, filename: n, strict: false, localsName: 'locals' });
  t.compile();
  tpl += `  ${JSON.stringify(n)}: (function (locals, escapeFn, include) {\n${t.source}\n}),\n`;
}
tpl += '};\n';
fs.writeFileSync(path.join(out, 'templates.js'), tpl);

// 2. sql.js WebAssembly, inlined (the artifact sandbox blocks fetching it).
const wasm = fs.readFileSync(path.join(root, 'node_modules/sql.js/dist/sql-wasm.wasm'));
fs.writeFileSync(path.join(out, 'wasm.js'), `module.exports = { WASM_B64: ${JSON.stringify(wasm.toString('base64'))} };\n`);

// 3. Bundle.
const shim = (f) => path.join(__dirname, 'shims', f);
const result = esbuild.buildSync({
  entryPoints: [path.join(__dirname, 'main.js')],
  bundle: true,
  write: false,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  minify: true,
  legalComments: 'none',
  inject: [shim('buffer-global.js')],
  define: { 'process.env.COACH_DESK_TODAY': 'undefined', 'process.env.NODE_ENV': '"production"', __dirname: '"/"' },
  alias: {
    'better-sqlite3': shim('better-sqlite3.js'),
    express: shim('express.js'),
    multer: shim('multer.js'),
    pdfkit: shim('pdfkit.js'),
    exceljs: shim('exceljs.js'),
    'csv-parse/sync': path.join(root, 'node_modules/csv-parse/dist/esm/sync.js'),
    path: shim('misc.js'),
    fs: shim('misc.js'),
    os: shim('misc.js'),
    crypto: shim('misc.js'),
  },
  logLevel: 'warning',
});
const js = result.outputFiles[0].text;

// 4. Page: title, styles (shared stylesheet + artifact extras), libraries from cdnjs, app.
const css = fs.readFileSync(path.join(root, 'public/style.css'), 'utf8');
const extra = `
#save-status { position: fixed; right: 12px; bottom: calc(12px + env(safe-area-inset-bottom, 0px)); z-index: 20; background: var(--card); color: var(--muted); border: 1px solid var(--line); border-radius: 999px; padding: 4px 12px; font-size: 12px; }
#save-status[data-bad="1"] { color: var(--red); border-color: var(--red-line); background: var(--red-bg); }
#modal { position: fixed; inset: 0; z-index: 30; background: rgba(8, 14, 24, .55); display: grid; place-items: center; padding: 16px; }
#modal[hidden] { display: none; }
#modal .box { background: var(--card); color: var(--ink); border-radius: 12px; padding: 16px; width: min(760px, 100%); max-height: 90vh; display: grid; gap: 10px; }
#modal textarea { min-height: 260px; font-family: ui-monospace, Consolas, monospace; font-size: 12px; }
#modal h2 { margin: 0; }
.sp { max-width: 180mm; margin: 0 auto; }
#boot { padding: 40px 16px; color: var(--muted); }
`;
const html = `<title>Coach Desk</title>
<style>
${css}
${extra}
</style>
<div id="app"><div id="boot">Opening Coach Desk…</div></div>
<div id="save-status" role="status" aria-live="polite">Loading…</div>
<div id="modal" hidden>
  <div class="box" role="dialog" aria-modal="true" aria-labelledby="modal-title">
    <h2 id="modal-title"></h2>
    <p class="small muted"></p>
    <textarea id="modal-text" readonly></textarea>
    <div class="actions"><button type="button" data-copy="modal-text">Copy</button><button type="button" class="secondary" data-close-modal>Close</button></div>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.4.0/exceljs.min.js"></script>
<script>
${tpl.replace(/<\/script/gi, '<\\/script')}
</script>
<script>
${js.replace(/<\/script/gi, '<\\/script')}
</script>
`;
const dest = path.join(__dirname, 'dist', 'coach-desk.html');
fs.writeFileSync(dest, html);
console.log(`Wrote ${path.relative(root, dest)} (${(html.length / 1024 / 1024).toFixed(2)} MB)`);
